// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/Steadypim/rocket-factory/payment/internal/model"
)

// NewMockPaymentService creates a new instance of MockPaymentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentService {
	mock := &MockPaymentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPaymentService is an autogenerated mock type for the PaymentService type
type MockPaymentService struct {
	mock.Mock
}

type MockPaymentService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentService) EXPECT() *MockPaymentService_Expecter {
	return &MockPaymentService_Expecter{mock: &_m.Mock}
}

// PayOrder provides a mock function for the type MockPaymentService
func (_mock *MockPaymentService) PayOrder(ctx context.Context, payment model.Payment) (*model.Payment, error) {
	ret := _mock.Called(ctx, payment)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 *model.Payment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Payment) (*model.Payment, error)); ok {
		return returnFunc(ctx, payment)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Payment) *model.Payment); ok {
		r0 = returnFunc(ctx, payment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Payment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.Payment) error); ok {
		r1 = returnFunc(ctx, payment)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPaymentService_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type MockPaymentService_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - payment model.Payment
func (_e *MockPaymentService_Expecter) PayOrder(ctx interface{}, payment interface{}) *MockPaymentService_PayOrder_Call {
	return &MockPaymentService_PayOrder_Call{Call: _e.mock.On("PayOrder", ctx, payment)}
}

func (_c *MockPaymentService_PayOrder_Call) Run(run func(ctx context.Context, payment model.Payment)) *MockPaymentService_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Payment
		if args[1] != nil {
			arg1 = args[1].(model.Payment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPaymentService_PayOrder_Call) Return(payment1 *model.Payment, err error) *MockPaymentService_PayOrder_Call {
	_c.Call.Return(payment1, err)
	return _c
}

func (_c *MockPaymentService_PayOrder_Call) RunAndReturn(run func(ctx context.Context, payment model.Payment) (*model.Payment, error)) *MockPaymentService_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}
