// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	order0 "github.com/Steadypim/rocket-factory/order/internal/domain/order"
	"github.com/Steadypim/rocket-factory/order/internal/service/order"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderService creates a new instance of MockOrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderService {
	mock := &MockOrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderService is an autogenerated mock type for the orderService type
type MockOrderService struct {
	mock.Mock
}

type MockOrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderService) EXPECT() *MockOrderService_Expecter {
	return &MockOrderService_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function for the type MockOrderService
func (_mock *MockOrderService) Cancel(ctx context.Context, orderID string) error {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderService_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type MockOrderService_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
func (_e *MockOrderService_Expecter) Cancel(ctx interface{}, orderID interface{}) *MockOrderService_Cancel_Call {
	return &MockOrderService_Cancel_Call{Call: _e.mock.On("Cancel", ctx, orderID)}
}

func (_c *MockOrderService_Cancel_Call) Run(run func(ctx context.Context, orderID string)) *MockOrderService_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderService_Cancel_Call) Return(err error) *MockOrderService_Cancel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderService_Cancel_Call) RunAndReturn(run func(ctx context.Context, orderID string) error) *MockOrderService_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockOrderService
func (_mock *MockOrderService) Create(ctx context.Context, params order.CreateParams) (order.CreateResult, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 order.CreateResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, order.CreateParams) (order.CreateResult, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, order.CreateParams) order.CreateResult); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(order.CreateResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, order.CreateParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOrderService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - params order.CreateParams
func (_e *MockOrderService_Expecter) Create(ctx interface{}, params interface{}) *MockOrderService_Create_Call {
	return &MockOrderService_Create_Call{Call: _e.mock.On("Create", ctx, params)}
}

func (_c *MockOrderService_Create_Call) Run(run func(ctx context.Context, params order.CreateParams)) *MockOrderService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 order.CreateParams
		if args[1] != nil {
			arg1 = args[1].(order.CreateParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderService_Create_Call) Return(createResult order.CreateResult, err error) *MockOrderService_Create_Call {
	_c.Call.Return(createResult, err)
	return _c
}

func (_c *MockOrderService_Create_Call) RunAndReturn(run func(ctx context.Context, params order.CreateParams) (order.CreateResult, error)) *MockOrderService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockOrderService
func (_mock *MockOrderService) Get(ctx context.Context, orderID string) (order0.Order, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 order0.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (order0.Order, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) order0.Order); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Get(0).(order0.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockOrderService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
func (_e *MockOrderService_Expecter) Get(ctx interface{}, orderID interface{}) *MockOrderService_Get_Call {
	return &MockOrderService_Get_Call{Call: _e.mock.On("Get", ctx, orderID)}
}

func (_c *MockOrderService_Get_Call) Run(run func(ctx context.Context, orderID string)) *MockOrderService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderService_Get_Call) Return(order1 order0.Order, err error) *MockOrderService_Get_Call {
	_c.Call.Return(order1, err)
	return _c
}

func (_c *MockOrderService_Get_Call) RunAndReturn(run func(ctx context.Context, orderID string) (order0.Order, error)) *MockOrderService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Pay provides a mock function for the type MockOrderService
func (_mock *MockOrderService) Pay(ctx context.Context, params order.PayParams) (string, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Pay")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, order.PayParams) (string, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, order.PayParams) string); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, order.PayParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderService_Pay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pay'
type MockOrderService_Pay_Call struct {
	*mock.Call
}

// Pay is a helper method to define mock.On call
//   - ctx context.Context
//   - params order.PayParams
func (_e *MockOrderService_Expecter) Pay(ctx interface{}, params interface{}) *MockOrderService_Pay_Call {
	return &MockOrderService_Pay_Call{Call: _e.mock.On("Pay", ctx, params)}
}

func (_c *MockOrderService_Pay_Call) Run(run func(ctx context.Context, params order.PayParams)) *MockOrderService_Pay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 order.PayParams
		if args[1] != nil {
			arg1 = args[1].(order.PayParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderService_Pay_Call) Return(s string, err error) *MockOrderService_Pay_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockOrderService_Pay_Call) RunAndReturn(run func(ctx context.Context, params order.PayParams) (string, error)) *MockOrderService_Pay_Call {
	_c.Call.Return(run)
	return _c
}
