// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Steadypim/rocket-factory/payment/internal/domain/payment"
	"github.com/Steadypim/rocket-factory/shared/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPaymentRepository creates a new instance of MockPaymentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentRepository {
	mock := &MockPaymentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPaymentRepository is an autogenerated mock type for the paymentRepository type
type MockPaymentRepository struct {
	mock.Mock
}

type MockPaymentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentRepository) EXPECT() *MockPaymentRepository_Expecter {
	return &MockPaymentRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockPaymentRepository
func (_mock *MockPaymentRepository) Create(ctx context.Context, orderID string, userID string, paymentMethod model.PaymentMethod) (payment.Transaction, error) {
	ret := _mock.Called(ctx, orderID, userID, paymentMethod)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 payment.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, model.PaymentMethod) (payment.Transaction, error)); ok {
		return returnFunc(ctx, orderID, userID, paymentMethod)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, model.PaymentMethod) payment.Transaction); ok {
		r0 = returnFunc(ctx, orderID, userID, paymentMethod)
	} else {
		r0 = ret.Get(0).(payment.Transaction)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, model.PaymentMethod) error); ok {
		r1 = returnFunc(ctx, orderID, userID, paymentMethod)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPaymentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPaymentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
//   - userID string
//   - paymentMethod model.PaymentMethod
func (_e *MockPaymentRepository_Expecter) Create(ctx interface{}, orderID interface{}, userID interface{}, paymentMethod interface{}) *MockPaymentRepository_Create_Call {
	return &MockPaymentRepository_Create_Call{Call: _e.mock.On("Create", ctx, orderID, userID, paymentMethod)}
}

func (_c *MockPaymentRepository_Create_Call) Run(run func(ctx context.Context, orderID string, userID string, paymentMethod model.PaymentMethod)) *MockPaymentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 model.PaymentMethod
		if args[3] != nil {
			arg3 = args[3].(model.PaymentMethod)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPaymentRepository_Create_Call) Return(transaction payment.Transaction, err error) *MockPaymentRepository_Create_Call {
	_c.Call.Return(transaction, err)
	return _c
}

func (_c *MockPaymentRepository_Create_Call) RunAndReturn(run func(ctx context.Context, orderID string, userID string, paymentMethod model.PaymentMethod) (payment.Transaction, error)) *MockPaymentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}
