// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Steadypim/rocket-factory/shared/pkg/proto/inventory/v1"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewMockInventoryGRPCClient creates a new instance of MockInventoryGRPCClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInventoryGRPCClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInventoryGRPCClient {
	mock := &MockInventoryGRPCClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInventoryGRPCClient is an autogenerated mock type for the grpcClient type
type MockInventoryGRPCClient struct {
	mock.Mock
}

type MockInventoryGRPCClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInventoryGRPCClient) EXPECT() *MockInventoryGRPCClient_Expecter {
	return &MockInventoryGRPCClient_Expecter{mock: &_m.Mock}
}

// ListParts provides a mock function for the type MockInventoryGRPCClient
func (_mock *MockInventoryGRPCClient) ListParts(ctx context.Context, request *inventory_v1.ListPartsRequest, opts ...grpc.CallOption) (*inventory_v1.ListPartsResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, request, opts)
	} else {
		tmpRet = _mock.Called(ctx, request)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 *inventory_v1.ListPartsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *inventory_v1.ListPartsRequest, ...grpc.CallOption) (*inventory_v1.ListPartsResponse, error)); ok {
		return returnFunc(ctx, request, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *inventory_v1.ListPartsRequest, ...grpc.CallOption) *inventory_v1.ListPartsResponse); ok {
		r0 = returnFunc(ctx, request, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*inventory_v1.ListPartsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *inventory_v1.ListPartsRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, request, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInventoryGRPCClient_ListParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListParts'
type MockInventoryGRPCClient_ListParts_Call struct {
	*mock.Call
}

// ListParts is a helper method to define mock.On call
//   - ctx context.Context
//   - request *inventory_v1.ListPartsRequest
//   - opts ...grpc.CallOption
func (_e *MockInventoryGRPCClient_Expecter) ListParts(ctx interface{}, request interface{}, opts ...interface{}) *MockInventoryGRPCClient_ListParts_Call {
	return &MockInventoryGRPCClient_ListParts_Call{Call: _e.mock.On("ListParts",
		append([]interface{}{ctx, request}, opts...)...)}
}

func (_c *MockInventoryGRPCClient_ListParts_Call) Run(run func(ctx context.Context, request *inventory_v1.ListPartsRequest, opts ...grpc.CallOption)) *MockInventoryGRPCClient_ListParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *inventory_v1.ListPartsRequest
		if args[1] != nil {
			arg1 = args[1].(*inventory_v1.ListPartsRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockInventoryGRPCClient_ListParts_Call) Return(listPartsResponse *inventory_v1.ListPartsResponse, err error) *MockInventoryGRPCClient_ListParts_Call {
	_c.Call.Return(listPartsResponse, err)
	return _c
}

func (_c *MockInventoryGRPCClient_ListParts_Call) RunAndReturn(run func(ctx context.Context, request *inventory_v1.ListPartsRequest, opts ...grpc.CallOption) (*inventory_v1.ListPartsResponse, error)) *MockInventoryGRPCClient_ListParts_Call {
	_c.Call.Return(run)
	return _c
}
