// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Steadypim/rocket-factory/shared/pkg/proto/payment/v1"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewMockPaymentGRPCClient creates a new instance of MockPaymentGRPCClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentGRPCClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentGRPCClient {
	mock := &MockPaymentGRPCClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPaymentGRPCClient is an autogenerated mock type for the grpcClient type
type MockPaymentGRPCClient struct {
	mock.Mock
}

type MockPaymentGRPCClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentGRPCClient) EXPECT() *MockPaymentGRPCClient_Expecter {
	return &MockPaymentGRPCClient_Expecter{mock: &_m.Mock}
}

// PayOrder provides a mock function for the type MockPaymentGRPCClient
func (_mock *MockPaymentGRPCClient) PayOrder(ctx context.Context, request *payment_v1.PayOrderRequest, opts ...grpc.CallOption) (*payment_v1.PayOrderResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, request, opts)
	} else {
		tmpRet = _mock.Called(ctx, request)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 *payment_v1.PayOrderResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *payment_v1.PayOrderRequest, ...grpc.CallOption) (*payment_v1.PayOrderResponse, error)); ok {
		return returnFunc(ctx, request, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *payment_v1.PayOrderRequest, ...grpc.CallOption) *payment_v1.PayOrderResponse); ok {
		r0 = returnFunc(ctx, request, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*payment_v1.PayOrderResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *payment_v1.PayOrderRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, request, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPaymentGRPCClient_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type MockPaymentGRPCClient_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - request *payment_v1.PayOrderRequest
//   - opts ...grpc.CallOption
func (_e *MockPaymentGRPCClient_Expecter) PayOrder(ctx interface{}, request interface{}, opts ...interface{}) *MockPaymentGRPCClient_PayOrder_Call {
	return &MockPaymentGRPCClient_PayOrder_Call{Call: _e.mock.On("PayOrder",
		append([]interface{}{ctx, request}, opts...)...)}
}

func (_c *MockPaymentGRPCClient_PayOrder_Call) Run(run func(ctx context.Context, request *payment_v1.PayOrderRequest, opts ...grpc.CallOption)) *MockPaymentGRPCClient_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *payment_v1.PayOrderRequest
		if args[1] != nil {
			arg1 = args[1].(*payment_v1.PayOrderRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockPaymentGRPCClient_PayOrder_Call) Return(payOrderResponse *payment_v1.PayOrderResponse, err error) *MockPaymentGRPCClient_PayOrder_Call {
	_c.Call.Return(payOrderResponse, err)
	return _c
}

func (_c *MockPaymentGRPCClient_PayOrder_Call) RunAndReturn(run func(ctx context.Context, request *payment_v1.PayOrderRequest, opts ...grpc.CallOption) (*payment_v1.PayOrderResponse, error)) *MockPaymentGRPCClient_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}
