// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Steadypim/rocket-factory/inventory/internal/domain/inventory"
	mock "github.com/stretchr/testify/mock"
)

// NewMockInventoryRepository creates a new instance of MockInventoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInventoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInventoryRepository {
	mock := &MockInventoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInventoryRepository is an autogenerated mock type for the inventoryRepository type
type MockInventoryRepository struct {
	mock.Mock
}

type MockInventoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInventoryRepository) EXPECT() *MockInventoryRepository_Expecter {
	return &MockInventoryRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockInventoryRepository
func (_mock *MockInventoryRepository) Get(ctx context.Context, partID string) (inventory.Part, error) {
	ret := _mock.Called(ctx, partID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 inventory.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (inventory.Part, error)); ok {
		return returnFunc(ctx, partID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) inventory.Part); ok {
		r0 = returnFunc(ctx, partID)
	} else {
		r0 = ret.Get(0).(inventory.Part)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, partID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInventoryRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockInventoryRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - partID string
func (_e *MockInventoryRepository_Expecter) Get(ctx interface{}, partID interface{}) *MockInventoryRepository_Get_Call {
	return &MockInventoryRepository_Get_Call{Call: _e.mock.On("Get", ctx, partID)}
}

func (_c *MockInventoryRepository_Get_Call) Run(run func(ctx context.Context, partID string)) *MockInventoryRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInventoryRepository_Get_Call) Return(part inventory.Part, err error) *MockInventoryRepository_Get_Call {
	_c.Call.Return(part, err)
	return _c
}

func (_c *MockInventoryRepository_Get_Call) RunAndReturn(run func(ctx context.Context, partID string) (inventory.Part, error)) *MockInventoryRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockInventoryRepository
func (_mock *MockInventoryRepository) List(ctx context.Context, filter inventory.Filter) ([]inventory.Part, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []inventory.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, inventory.Filter) ([]inventory.Part, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, inventory.Filter) []inventory.Part); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]inventory.Part)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, inventory.Filter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInventoryRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockInventoryRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter inventory.Filter
func (_e *MockInventoryRepository_Expecter) List(ctx interface{}, filter interface{}) *MockInventoryRepository_List_Call {
	return &MockInventoryRepository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockInventoryRepository_List_Call) Run(run func(ctx context.Context, filter inventory.Filter)) *MockInventoryRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 inventory.Filter
		if args[1] != nil {
			arg1 = args[1].(inventory.Filter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInventoryRepository_List_Call) Return(parts []inventory.Part, err error) *MockInventoryRepository_List_Call {
	_c.Call.Return(parts, err)
	return _c
}

func (_c *MockInventoryRepository_List_Call) RunAndReturn(run func(ctx context.Context, filter inventory.Filter) ([]inventory.Part, error)) *MockInventoryRepository_List_Call {
	_c.Call.Return(run)
	return _c
}
