// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Steadypim/rocket-factory/payment/internal/service/payment"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPaymentService creates a new instance of MockPaymentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentService {
	mock := &MockPaymentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPaymentService is an autogenerated mock type for the paymentService type
type MockPaymentService struct {
	mock.Mock
}

type MockPaymentService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentService) EXPECT() *MockPaymentService_Expecter {
	return &MockPaymentService_Expecter{mock: &_m.Mock}
}

// Pay provides a mock function for the type MockPaymentService
func (_mock *MockPaymentService) Pay(ctx context.Context, params payment.PayParams) (payment.PayResult, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Pay")
	}

	var r0 payment.PayResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, payment.PayParams) (payment.PayResult, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, payment.PayParams) payment.PayResult); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(payment.PayResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, payment.PayParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPaymentService_Pay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pay'
type MockPaymentService_Pay_Call struct {
	*mock.Call
}

// Pay is a helper method to define mock.On call
//   - ctx context.Context
//   - params payment.PayParams
func (_e *MockPaymentService_Expecter) Pay(ctx interface{}, params interface{}) *MockPaymentService_Pay_Call {
	return &MockPaymentService_Pay_Call{Call: _e.mock.On("Pay", ctx, params)}
}

func (_c *MockPaymentService_Pay_Call) Run(run func(ctx context.Context, params payment.PayParams)) *MockPaymentService_Pay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 payment.PayParams
		if args[1] != nil {
			arg1 = args[1].(payment.PayParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPaymentService_Pay_Call) Return(payResult payment.PayResult, err error) *MockPaymentService_Pay_Call {
	_c.Call.Return(payResult, err)
	return _c
}

func (_c *MockPaymentService_Pay_Call) RunAndReturn(run func(ctx context.Context, params payment.PayParams) (payment.PayResult, error)) *MockPaymentService_Pay_Call {
	_c.Call.Return(run)
	return _c
}
