// Package order_v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package order_v1

// Defines values for OrderPaymentMethod.
const (
	OrderPaymentMethodPAYMENTMETHODCARD          OrderPaymentMethod = "PAYMENT_METHOD_CARD"
	OrderPaymentMethodPAYMENTMETHODCREDITCARD    OrderPaymentMethod = "PAYMENT_METHOD_CREDIT_CARD"
	OrderPaymentMethodPAYMENTMETHODINVESTORMONEY OrderPaymentMethod = "PAYMENT_METHOD_INVESTOR_MONEY"
	OrderPaymentMethodPAYMENTMETHODSBP           OrderPaymentMethod = "PAYMENT_METHOD_SBP"
	OrderPaymentMethodPAYMENTMETHODUNKNOWN       OrderPaymentMethod = "PAYMENT_METHOD_UNKNOWN"
)

// Valid indicates whether the value is a known member of the OrderPaymentMethod enum.
func (e OrderPaymentMethod) Valid() bool {
	switch e {
	case OrderPaymentMethodPAYMENTMETHODCARD:
		return true
	case OrderPaymentMethodPAYMENTMETHODCREDITCARD:
		return true
	case OrderPaymentMethodPAYMENTMETHODINVESTORMONEY:
		return true
	case OrderPaymentMethodPAYMENTMETHODSBP:
		return true
	case OrderPaymentMethodPAYMENTMETHODUNKNOWN:
		return true
	default:
		return false
	}
}

// Defines values for OrderStatus.
const (
	CANCELLED      OrderStatus = "CANCELLED"
	PAID           OrderStatus = "PAID"
	PENDINGPAYMENT OrderStatus = "PENDING_PAYMENT"
)

// Valid indicates whether the value is a known member of the OrderStatus enum.
func (e OrderStatus) Valid() bool {
	switch e {
	case CANCELLED:
		return true
	case PAID:
		return true
	case PENDINGPAYMENT:
		return true
	default:
		return false
	}
}

// Defines values for PayOrderRequestPaymentMethod.
const (
	PayOrderRequestPaymentMethodPAYMENTMETHODCARD          PayOrderRequestPaymentMethod = "PAYMENT_METHOD_CARD"
	PayOrderRequestPaymentMethodPAYMENTMETHODCREDITCARD    PayOrderRequestPaymentMethod = "PAYMENT_METHOD_CREDIT_CARD"
	PayOrderRequestPaymentMethodPAYMENTMETHODINVESTORMONEY PayOrderRequestPaymentMethod = "PAYMENT_METHOD_INVESTOR_MONEY"
	PayOrderRequestPaymentMethodPAYMENTMETHODSBP           PayOrderRequestPaymentMethod = "PAYMENT_METHOD_SBP"
)

// Valid indicates whether the value is a known member of the PayOrderRequestPaymentMethod enum.
func (e PayOrderRequestPaymentMethod) Valid() bool {
	switch e {
	case PayOrderRequestPaymentMethodPAYMENTMETHODCARD:
		return true
	case PayOrderRequestPaymentMethodPAYMENTMETHODCREDITCARD:
		return true
	case PayOrderRequestPaymentMethodPAYMENTMETHODINVESTORMONEY:
		return true
	case PayOrderRequestPaymentMethodPAYMENTMETHODSBP:
		return true
	default:
		return false
	}
}

// BadRequestError defines model for BadRequestError.
type BadRequestError struct {
	// Code HTTP-код ошибки
	Code int `json:"code"`

	// Message Описание ошибки
	Message string `json:"message"`
}

// CreateOrderRequest defines model for CreateOrderRequest.
type CreateOrderRequest struct {
	// PartUuids список id частей
	PartUuids []string `json:"part_uuids"`

	// UserUuid id пользователя
	UserUuid string `json:"user_uuid"`
}

// CreatedOrder defines model for CreatedOrder.
type CreatedOrder struct {
	// TotalPrice общая цена
	TotalPrice float32 `json:"total_price,omitempty"`

	// Uuid id заказа
	Uuid string `json:"uuid,omitempty"`
}

// GenericError defines model for GenericError.
type GenericError struct {
	// Code HTTP-код ошибки
	Code int `json:"code,omitempty"`

	// Message Описание ошибки
	Message string `json:"message,omitempty"`
}

// InternalServerError defines model for InternalServerError.
type InternalServerError struct {
	// Code HTTP-код ошибки
	Code int `json:"code"`

	// Message Описание ошибки
	Message string `json:"message"`
}

// NotFoundError defines model for NotFoundError.
type NotFoundError struct {
	// Code HTTP-код ошибки
	Code int `json:"code"`

	// Message Описание ошибки
	Message string `json:"message"`
}

// Order defines model for Order.
type Order struct {
	// OrderUuid The unique identifier for the order
	OrderUuid string `json:"order_uuid,omitempty"`

	// PartUuids The unique identifiers for the parts
	PartUuids []string `json:"part_uuids,omitempty"`

	// PaymentMethod The payment method used for the transaction
	PaymentMethod OrderPaymentMethod `json:"payment_method,omitempty"`

	// Status The status of the order
	Status OrderStatus `json:"status,omitempty"`

	// TotalPrice The total price of the order
	TotalPrice float32 `json:"total_price,omitempty"`

	// TransactionUuid The unique identifier for the transaction
	TransactionUuid string `json:"transaction_uuid,omitempty"`

	// UserUuid The unique identifier for the user
	UserUuid string `json:"user_uuid,omitempty"`
}

// OrderPaymentMethod The payment method used for the transaction
type OrderPaymentMethod string

// OrderStatus The status of the order
type OrderStatus string

// OrderPayment defines model for OrderPayment.
type OrderPayment struct {
	// TransactionUuid id заказа
	TransactionUuid string `json:"transaction_uuid"`
}

// PayOrderRequest defines model for PayOrderRequest.
type PayOrderRequest struct {
	// PaymentMethod The payment method to use for the order.
	PaymentMethod PayOrderRequestPaymentMethod `json:"payment_method"`
}

// PayOrderRequestPaymentMethod The payment method to use for the order.
type PayOrderRequestPaymentMethod string
